# -*- coding: utf-8 -*-
"""XGBoost_TA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc9h3uQ7IpOk1qxavrND2BfsfZUzC0Ck
"""

!pip install -q "cdsapi>=0.7.7" xarray netCDF4 pandas numpy openpyxl xgboost

import os

# GANTI bagian ini dengan token CDS kamu
CDS_TOKEN = "90821c76-cf17-4ae8-aa47-64048d50256c"

cdsapirc = f"""
url: https://cds.climate.copernicus.eu/api
key: {CDS_TOKEN}
"""

with open("/root/.cdsapirc", "w") as f:
    f.write(cdsapirc.strip())

print("File .cdsapirc berhasil dibuat.")

import cdsapi

client = cdsapi.Client()

# Koordinat Pos Pantau Depok 2 Sungai Ciliwung
lat_pos = -6.398695
lon_pos = 106.837371

# Area kecil sekitar pos, diperluas menjadi 0.3x0.3 derajat (sesuai resolusi ERA5 0.25 derajat)
# Format ERA5: [utara, barat, selatan, timur]
area_pos_depok2 = [
    lat_pos + 0.15, lon_pos - 0.15,
    lat_pos - 0.15, lon_pos + 0.15
]

print(area_pos_depok2)

dataset = "reanalysis-era5-single-levels"

times = [f"{h:02d}:00" for h in range(24)]

daftar_download = [
    {
        "year": "2025",
        "month": "11",
        "days": [f"{d:02d}" for d in range(1, 31)],
        "target": "era5_pos_depok2_november_2025.nc"
    },
    {
        "year": "2025",
        "month": "12",
        "days": [f"{d:02d}" for d in range(1, 32)],
        "target": "era5_pos_depok2_desember_2025.nc"
    },
    {
        "year": "2026",
        "month": "01",
        "days": [f"{d:02d}" for d in range(1, 32)],
        "target": "era5_pos_depok2_januari_2026.nc"
    },
    {
        "year": "2026",
        "month": "02",
        "days": [f"{d:02d}" for d in range(1, 29)],
        "target": "era5_pos_depok2_februari_2026.nc"
    },
    {
        "year": "2026",
        "month": "03",
        "days": [f"{d:02d}" for d in range(1, 32)],
        "target": "era5_pos_depok2_maret_2026.nc"
    }
]

for item in daftar_download:
    request = {
        "product_type": ["reanalysis"],
        "variable": ["total_precipitation"],
        "year": [item["year"]],
        "month": [item["month"]],
        "day": item["days"],
        "time": times,
        "data_format": "netcdf",
        "download_format": "unarchived",
        "area": area_pos_depok2
    }

    print(f"Mulai download: {item['target']}")
    client.retrieve(dataset, request, item["target"])
    print(f"Selesai download: {item['target']}")

import xarray as xr
import pandas as pd
import numpy as np

files_nc = [
    "era5_pos_depok2_november_2025.nc",
    "era5_pos_depok2_desember_2025.nc",
    "era5_pos_depok2_januari_2026.nc",
    "era5_pos_depok2_februari_2026.nc",
    "era5_pos_depok2_maret_2026.nc"
]

rain_all = []

for file in files_nc:
    ds = xr.open_dataset(file)

    print("\nFile:", file)
    print("Variabel:", list(ds.data_vars))
    print("Koordinat:", list(ds.coords))

    if "tp" not in ds.data_vars:
        raise ValueError(f"Variabel tp tidak ditemukan pada {file}")

    if "valid_time" in ds.coords:
        time_name = "valid_time"
    elif "time" in ds.coords:
        time_name = "time"
    else:
        raise ValueError(f"Koordinat waktu tidak ditemukan pada {file}")

    # Rata-rata hujan area kecil sekitar Pos Depok 2
    tp_area_mean = ds["tp"].mean(dim=["latitude", "longitude"])

    # Ambil grid terdekat ke koordinat Pos Depok 2
    tp_nearest = ds["tp"].sel(
        latitude=lat_pos,
        longitude=lon_pos,
        method="nearest"
    )

    df_area = tp_area_mean.to_dataframe(name="tp_area_mean").reset_index()
    df_near = tp_nearest.to_dataframe(name="tp_nearest").reset_index()

    df_area["datetime_utc"] = pd.to_datetime(df_area[time_name])
    df_near["datetime_utc"] = pd.to_datetime(df_near[time_name])

    df = pd.merge(
        df_area[["datetime_utc", "tp_area_mean"]],
        df_near[["datetime_utc", "tp_nearest"]],
        on="datetime_utc",
        how="inner"
    )

    # ERA5 total precipitation satuannya meter, dikonversi menjadi mm
    df["Hujan_ERA5_area_mean_mm"] = df["tp_area_mean"] * 1000
    df["Hujan_ERA5_nearest_mm"] = df["tp_nearest"] * 1000

    # Konversi UTC ke WIB
    df["datetime"] = df["datetime_utc"] + pd.Timedelta(hours=7)

    rain_all.append(df)

era5_hujan = pd.concat(rain_all, ignore_index=True)
era5_hujan = era5_hujan.sort_values("datetime").reset_index(drop=True)

# Filter periode WIB yang benar
era5_hujan = era5_hujan[
    (era5_hujan["datetime"] >= "2025-11-01 00:00:00") &
    (era5_hujan["datetime"] <= "2026-03-31 23:00:00")
].copy()

era5_hujan = era5_hujan.reset_index(drop=True)

era5_hujan["Tanggal"] = era5_hujan["datetime"].dt.strftime("%m/%d/%Y")
era5_hujan["Pukul"] = era5_hujan["datetime"].dt.strftime("%H:%M")

era5_hujan = era5_hujan[
    [
        "datetime",
        "datetime_utc",
        "Tanggal",
        "Pukul",
        "Hujan_ERA5_area_mean_mm",
        "Hujan_ERA5_nearest_mm"
    ]
]

display(era5_hujan.head())
display(era5_hujan.tail())

print("Jumlah data ERA5:", era5_hujan.shape)

output_era5 = "era5_hujan_pos_depok2_nov2025_mar2026_wib.csv"

era5_hujan.to_csv(output_era5, index=False)

print("File ERA5 berhasil dibuat:", output_era5)

from google.colab import files

files.download(output_era5)

!pip install -q pandas numpy openpyxl

import re
import pandas as pd
import numpy as np
from google.colab import files
import matplotlib.pyplot as plt

from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

uploaded = files.upload()

list(uploaded.keys())

nama_file = "dataset_pos_depok2_nov2025_march2026.csv"

df = pd.read_csv(nama_file, sep=';')

display(df.head())
display(df.tail())

print(df.columns)
print(df.shape)

df["Tanggal"] = df["Tanggal"].astype(str)
df["Pukul"] = df["Pukul"].astype(str)

df["datetime"] = pd.to_datetime(
    df["Tanggal"] + " " + df["Pukul"],
    dayfirst=False,
    errors="coerce"
)

for kolom in ["Tinggi", "Hujan", "tinggi_lag1", "hujan_lag1"]:
    df[kolom] = pd.to_numeric(df[kolom], errors="coerce")

df = df.sort_values("datetime").reset_index(drop=True)

print("Jumlah datetime NaT:", df["datetime"].isna().sum())
print("Rentang waktu:", df["datetime"].min(), "sampai", df["datetime"].max())
print("\nMissing value:")
print(df.isna().sum())

display(df.head(20))

data_mencurigakan = df[
    (df["Tinggi"].notna()) &
    ((df["Tinggi"] < 50) | (df["Tinggi"] > 350))
]

display(data_mencurigakan)

df.loc[df["Tinggi"] < 50, "Tinggi"] = np.nan

df["Tinggi"] = df["Tinggi"].interpolate(method="linear")
df["Hujan"] = df["Hujan"].fillna(0)

print(df[["Tinggi", "Hujan"]].isna().sum())

df["tinggi_lag1"] = df["Tinggi"].shift(1)
df["hujan_lag1"] = df["Hujan"].shift(1)

df = df.dropna(subset=["Tinggi", "Hujan", "tinggi_lag1", "hujan_lag1"]).reset_index(drop=True)

display(df.head(20))

df_model = df.copy()

for lag in [1, 2, 3, 6, 12, 24]:
    df_model[f"tinggi_lag{lag}"] = df_model["Tinggi"].shift(lag)
    df_model[f"hujan_lag{lag}"] = df_model["Hujan"].shift(lag)

df_model["hujan_3jam"] = df_model["Hujan"].rolling(3).sum()
df_model["hujan_6jam"] = df_model["Hujan"].rolling(6).sum()
df_model["hujan_12jam"] = df_model["Hujan"].rolling(12).sum()
df_model["hujan_24jam"] = df_model["Hujan"].rolling(24).sum()

# Target prediksi 1 jam ke depan
df_model["target_tinggi_1jam"] = df_model["Tinggi"].shift(-1)

df_model = df_model.dropna().reset_index(drop=True)

print(df_model.shape)
display(df_model.head())

fitur = [
    "Tinggi",
    "Hujan",
    "tinggi_lag1",
    "tinggi_lag2",
    "tinggi_lag3",
    "tinggi_lag6",
    "tinggi_lag12",
    "tinggi_lag24",
    "hujan_lag1",
    "hujan_lag2",
    "hujan_lag3",
    "hujan_lag6",
    "hujan_lag12",
    "hujan_lag24",
    "hujan_3jam",
    "hujan_6jam",
    "hujan_12jam",
    "hujan_24jam"
]

X = df_model[fitur]
y = df_model["target_tinggi_1jam"]

print("X:", X.shape)
print("y:", y.shape)

split_index = int(len(df_model) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

waktu_test = df_model["datetime"].iloc[split_index:]

print("Train:", X_train.shape)
print("Test :", X_test.shape)

print("Rentang train:", df_model["datetime"].iloc[:split_index].min(), "sampai", df_model["datetime"].iloc[:split_index].max())
print("Rentang test :", df_model["datetime"].iloc[split_index:].min(), "sampai", df_model["datetime"].iloc[split_index:].max())

baseline_pred = df_model["Tinggi"].iloc[split_index:]

r2_baseline = r2_score(y_test, baseline_pred)
mae_baseline = mean_absolute_error(y_test, baseline_pred)
rmse_baseline = np.sqrt(mean_squared_error(y_test, baseline_pred))

print("Baseline Persistence")
print("R2   :", r2_baseline)
print("MAE  :", mae_baseline)
print("RMSE :", rmse_baseline)

model = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_estimators=500,
    learning_rate=0.02,
    max_depth=2,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_alpha=0.1,
    reg_lambda=2,
    n_jobs=1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("XGBoost")
print("R2   :", r2)
print("MAE  :", mae)
print("RMSE :", rmse)

hasil = pd.DataFrame({
    "datetime": waktu_test.values,
    "Tinggi_Aktual": y_test.values,
    "Tinggi_Prediksi_XGBoost": y_pred,
    "Baseline": baseline_pred.values,
    "Error_XGBoost": y_test.values - y_pred,
    "Abs_Error_XGBoost": np.abs(y_test.values - y_pred)
})

display(hasil.head(20))

plt.figure(figsize=(14, 5))
plt.plot(hasil["datetime"], hasil["Tinggi_Aktual"], label="Aktual")
plt.plot(hasil["datetime"], hasil["Tinggi_Prediksi_XGBoost"], label="Prediksi XGBoost")
plt.plot(hasil["datetime"], hasil["Baseline"], label="Baseline", linestyle="--")
plt.xlabel("Waktu")
plt.ylabel("Tinggi Muka Air (cm)")
plt.title("Prediksi Tinggi Muka Air 1 Jam ke Depan")
plt.legend()
plt.grid(True)
plt.show()

importance = pd.DataFrame({
    "Fitur": fitur,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

display(importance)

plt.figure(figsize=(10, 5))
plt.barh(importance["Fitur"], importance["Importance"])
plt.xlabel("Importance")
plt.ylabel("Fitur")
plt.title("Feature Importance XGBoost")
plt.gca().invert_yaxis()
plt.grid(True)
plt.show()

plt.figure(figsize=(6, 6))

plt.scatter(
    hasil["Tinggi_Aktual"],
    hasil["Tinggi_Prediksi_XGBoost"],
    alpha=0.6
)

min_val = min(
    hasil["Tinggi_Aktual"].min(),
    hasil["Tinggi_Prediksi_XGBoost"].min()
)

max_val = max(
    hasil["Tinggi_Aktual"].max(),
    hasil["Tinggi_Prediksi_XGBoost"].max()
)

plt.plot([min_val, max_val], [min_val, max_val], linestyle="--")

plt.xlabel("Tinggi Aktual (cm)")
plt.ylabel("Tinggi Prediksi XGBoost (cm)")
plt.title("Scatter Aktual vs Prediksi XGBoost")
plt.grid(True)

plt.savefig("Scatter_Aktual_Prediksi.png", dpi=300, bbox_inches="tight")
plt.show()

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
import joblib

# ============================================================
# MODEL XGBOOST TANPA CURAH HUJAN
# Model ini dipakai untuk dashboard karena input dari IoT
# hanya menggunakan data tinggi_air dan fitur lag tinggi_air.
# ============================================================

fitur_tanpa_hujan = [
    "Tinggi",
    "tinggi_lag1",
    "tinggi_lag2",
    "tinggi_lag3",
    "tinggi_lag6",
    "tinggi_lag12",
    "tinggi_lag24"
]

X_tanpa_hujan = df_model[fitur_tanpa_hujan]
y_tanpa_hujan = df_model["target_tinggi_1jam"]

X_train_tanpa_hujan = X_tanpa_hujan.iloc[:split_index]
X_test_tanpa_hujan = X_tanpa_hujan.iloc[split_index:]

y_train_tanpa_hujan = y_tanpa_hujan.iloc[:split_index]
y_test_tanpa_hujan = y_tanpa_hujan.iloc[split_index:]

model_tanpa_hujan = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_estimators=500,
    learning_rate=0.02,
    max_depth=2,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_alpha=0.1,
    reg_lambda=2,
    n_jobs=1
)

model_tanpa_hujan.fit(X_train_tanpa_hujan, y_train_tanpa_hujan)

y_pred_tanpa_hujan = model_tanpa_hujan.predict(X_test_tanpa_hujan)

r2_tanpa_hujan = r2_score(y_test_tanpa_hujan, y_pred_tanpa_hujan)
mae_tanpa_hujan = mean_absolute_error(y_test_tanpa_hujan, y_pred_tanpa_hujan)
rmse_tanpa_hujan = np.sqrt(mean_squared_error(y_test_tanpa_hujan, y_pred_tanpa_hujan))

print("XGBoost Tanpa Curah Hujan")
print("R2   :", r2_tanpa_hujan)
print("MAE  :", mae_tanpa_hujan)
print("RMSE :", rmse_tanpa_hujan)

# Simpan model untuk dashboard Flask/VSCode
joblib.dump(model_tanpa_hujan, "xgboost_lag_model.pkl")

print("Model tanpa curah hujan berhasil disimpan sebagai xgboost_lag_model.pkl")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ============================================================
# MEMBUAT DATAFRAME HASIL PREDIKSI 3 MODEL
# ============================================================

# Jika kolom waktu di df_model bernama "datetime"
waktu_test = df_model["datetime"].iloc[split_index:]

hasil_model = pd.DataFrame({
    "waktu": np.array(waktu_test),
    "Tinggi_Aktual": np.array(y_test),
    "Baseline_Persistence": np.array(baseline_pred),
    "XGBoost_Dengan_Hujan": np.array(y_pred),
    "XGBoost_Tanpa_Hujan": np.array(y_pred_tanpa_hujan)
})

display(hasil_model.head(20))

# ============================================================
# VISUALISASI PERBANDINGAN MODEL
# ============================================================

plt.figure(figsize=(14, 5))

plt.plot(
    hasil_model["waktu"],
    hasil_model["Tinggi_Aktual"],
    label="Aktual"
)

plt.plot(
    hasil_model["waktu"],
    hasil_model["Baseline_Persistence"],
    label="Baseline Persistence",
    linestyle="--"
)

plt.plot(
    hasil_model["waktu"],
    hasil_model["XGBoost_Dengan_Hujan"],
    label="XGBoost dengan Curah Hujan"
)

plt.plot(
    hasil_model["waktu"],
    hasil_model["XGBoost_Tanpa_Hujan"],
    label="XGBoost tanpa Curah Hujan"
)

plt.xlabel("Waktu")
plt.ylabel("Tinggi Muka Air (cm)")
plt.title("Perbandingan Ketinggian Air Aktual dan Hasil Prediksi Model")
plt.legend()
plt.grid(True)
plt.tight_layout()

plt.savefig("Perbandingan_Model_XGBoost.png", dpi=300, bbox_inches="tight")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression

# ============================================================
# DATA PENGUJIAN PROTOTIPE
# ============================================================

data_prototipe = pd.DataFrame({
    "waktu": [
        "2026-06-03 00:00:00",
        "2026-06-03 01:00:00",
        "2026-06-03 02:00:00",
        "2026-06-03 03:00:00",
        "2026-06-03 04:00:00",
        "2026-06-03 05:00:00",
        "2026-06-03 06:00:00",
        "2026-06-03 07:00:00",
        "2026-06-03 08:00:00",
        "2026-06-03 09:00:00",
        "2026-06-03 10:00:00",
        "2026-06-03 11:00:00",
        "2026-06-03 12:00:00",
        "2026-06-03 13:00:00",
        "2026-06-03 14:00:00",
        "2026-06-03 15:00:00",
        "2026-06-03 16:00:00",
        "2026-06-03 17:00:00",
        "2026-06-03 18:00:00",
        "2026-06-03 19:00:00",
        "2026-06-03 20:00:00",
        "2026-06-03 21:00:00",
        "2026-06-03 22:00:00",
        "2026-06-03 23:00:00"
    ],
    "tinggi_air_acuan": [
        20, 20, 20,
        25, 25, 25,
        30, 30, 30,
        35, 35, 35,
        40, 40, 40,
        45, 45, 45,
        46, 46, 46,
        48, 48, 48
    ],
    "tinggi_air_sensor": [
        19.84, 20.05, 19.96,
        24.88, 25.10, 24.97,
        29.75, 30.08, 29.91,
        34.82, 35.11, 35.03,
        39.70, 40.16, 39.92,
        44.68, 45.05, 44.90,
        46.08, 46.22, 46.15,
        47.61, 47.82, 47.73
    ]
})

# ============================================================
# HITUNG ERROR, AKURASI, DAN R2
# ============================================================

data_prototipe["error"] = abs(
    data_prototipe["tinggi_air_sensor"] - data_prototipe["tinggi_air_acuan"]
)

data_prototipe["error_persen"] = (
    data_prototipe["error"] / data_prototipe["tinggi_air_acuan"]
) * 100

data_prototipe["akurasi_persen"] = 100 - data_prototipe["error_persen"]

r2_prototipe = r2_score(
    data_prototipe["tinggi_air_acuan"],
    data_prototipe["tinggi_air_sensor"]
)

mae_prototipe = data_prototipe["error"].mean()
akurasi_rata_rata = data_prototipe["akurasi_persen"].mean()

print("R2 prototipe =", r2_prototipe)
print("MAE prototipe =", mae_prototipe)
print("Akurasi rata-rata (%) =", akurasi_rata_rata)

display(data_prototipe)

# ============================================================
# REGRESI LINIER UNTUK GARIS FIT
# ============================================================

X = data_prototipe[["tinggi_air_acuan"]]
y = data_prototipe["tinggi_air_sensor"]

reg = LinearRegression()
reg.fit(X, y)

x_line = np.linspace(
    data_prototipe["tinggi_air_acuan"].min(),
    data_prototipe["tinggi_air_acuan"].max(),
    100
).reshape(-1, 1)

y_line = reg.predict(x_line)

# ============================================================
# SCATTER PLOT
# ============================================================

plt.figure(figsize=(7, 6))

plt.scatter(
    data_prototipe["tinggi_air_acuan"],
    data_prototipe["tinggi_air_sensor"],
    label="Data pengukuran sensor"
)

plt.plot(
    x_line,
    y_line,
    label=f"Regresi linier, R² = {r2_prototipe:.4f}"
)

plt.plot(
    x_line,
    x_line,
    linestyle="--",
    label="Garis ideal y = x"
)

plt.xlabel("Tinggi Air Acuan (cm)")
plt.ylabel("Tinggi Air Terukur Sensor (cm)")
plt.title("Scatter Plot Tinggi Air Acuan dan Terukur Prototipe")
plt.legend()
plt.grid(True)
plt.tight_layout()

plt.savefig("Scatter_Akurasi_Prototipe.jpg", dpi=300, bbox_inches="tight")
plt.show()

# ============================================================
# MODEL XGBOOST DASHBOARD BERDASARKAN DATA DRUM 20--75 CM
# File output: xgboost_lag_model.pkl
# Nama fitur dibuat sama dengan app.py:
# Tinggi, tinggi_lag1, tinggi_lag2, tinggi_lag3, tinggi_lag6, tinggi_lag12, tinggi_lag24
# ============================================================

import pandas as pd
import numpy as np
import joblib
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from google.colab import files

data_drum = pd.DataFrame({
    "waktu": [
        "2026-06-18 18:00:10",
        "2026-06-18 19:00:10",
        "2026-06-18 20:00:10",
        "2026-06-18 21:00:10",
        "2026-06-18 22:00:10",
        "2026-06-18 23:00:10",
        "2026-06-19 00:00:10",
        "2026-06-19 01:00:10",
        "2026-06-19 02:00:10",
        "2026-06-19 03:00:10",
        "2026-06-19 04:00:10",
        "2026-06-19 05:00:10",
        "2026-06-19 06:00:10",
        "2026-06-19 07:00:10",
        "2026-06-19 08:00:10",
        "2026-06-19 09:00:10",
        "2026-06-19 10:00:10",
        "2026-06-19 11:00:10",
        "2026-06-19 12:00:10",
        "2026-06-19 13:00:10",
        "2026-06-19 14:00:10",
        "2026-06-19 15:00:10",
        "2026-06-19 16:00:10",
        "2026-06-19 17:00:10",
        "2026-06-19 18:00:10",
        "2026-06-19 19:00:10",
        "2026-06-19 20:00:10",
        "2026-06-19 21:00:10",
        "2026-06-19 22:00:10",
        "2026-06-19 23:00:10"
    ],
    "Tinggi": [
        19.84, 21.05, 23.18, 25.36, 27.49, 29.82,
        31.27, 33.55, 35.72, 37.90, 39.66, 41.15,
        43.08, 45.23, 47.34, 49.52, 51.71, 53.82,
        55.98, 58.14, 60.27, 62.45, 64.62, 66.79,
        68.94, 70.53, 72.08, 73.16, 74.37, 75.09
    ]
})

data_drum["waktu"] = pd.to_datetime(data_drum["waktu"])
data_drum = data_drum.sort_values("waktu").reset_index(drop=True)

# Membuat fitur lag sesuai app.py
for lag in [1, 2, 3, 6, 12, 24]:
    data_drum[f"tinggi_lag{lag}"] = data_drum["Tinggi"].shift(lag)

# Target prediksi satu langkah waktu ke depan
data_drum["target_tinggi_1jam"] = data_drum["Tinggi"].shift(-1)

data_model_drum = data_drum.dropna().reset_index(drop=True)

fitur_tanpa_hujan = [
    "Tinggi",
    "tinggi_lag1",
    "tinggi_lag2",
    "tinggi_lag3",
    "tinggi_lag6",
    "tinggi_lag12",
    "tinggi_lag24"
]

X_drum = data_model_drum[fitur_tanpa_hujan]
y_drum = data_model_drum["target_tinggi_1jam"]

print("Jumlah data model drum:", len(data_model_drum))
display(data_model_drum)

model_drum = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_estimators=30,
    learning_rate=0.1,
    max_depth=1,
    subsample=1.0,
    colsample_bytree=1.0,
    n_jobs=1
)

model_drum.fit(X_drum, y_drum)

pred_drum = model_drum.predict(X_drum)

r2_drum = r2_score(y_drum, pred_drum)
mae_drum = mean_absolute_error(y_drum, pred_drum)
rmse_drum = np.sqrt(mean_squared_error(y_drum, pred_drum))

print("Evaluasi model dashboard data drum")
print("R2   :", r2_drum)
print("MAE  :", mae_drum)
print("RMSE :", rmse_drum)

hasil_drum = pd.DataFrame({
    "waktu": data_model_drum["waktu"],
    "aktual_target": y_drum,
    "prediksi_xgboost": pred_drum
})

display(hasil_drum)

# Simpan dengan nama yang sama seperti yang dibaca app.py
joblib.dump(model_drum, "xgboost_lag_model.pkl")
print("Model dashboard drum berhasil disimpan sebagai xgboost_lag_model.pkl")

files.download("xgboost_lag_model.pkl")

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))

plt.plot(
    hasil_drum["waktu"],
    hasil_drum["aktual_target"],
    marker="o",
    label="Tinggi Air Aktual"
)

plt.plot(
    hasil_drum["waktu"],
    hasil_drum["prediksi_xgboost"],
    marker="o",
    label="Prediksi XGBoost"
)

plt.title("Perbandingan Ketinggian Air Aktual dan Hasil Prediksi Model")
plt.xlabel("Waktu")
plt.ylabel("Ketinggian Air (cm)")
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# FULL KODE XGBOOST DENGAN DAN TANPA CURAH HUJAN
# + GRAFIK PERBANDINGAN AKTUAL VS DUA MODEL
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib

from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from google.colab import files

# ============================================================
# 1. DATA DRUM / PROTOTIPE
# ============================================================

df = pd.DataFrame({
    "waktu": [
        "2026-06-18 18:00:10",
        "2026-06-18 19:00:10",
        "2026-06-18 20:00:10",
        "2026-06-18 21:00:10",
        "2026-06-18 22:00:10",
        "2026-06-18 23:00:10",
        "2026-06-19 00:00:10",
        "2026-06-19 01:00:10",
        "2026-06-19 02:00:10",
        "2026-06-19 03:00:10",
        "2026-06-19 04:00:10",
        "2026-06-19 05:00:10",
        "2026-06-19 06:00:10",
        "2026-06-19 07:00:10",
        "2026-06-19 08:00:10",
        "2026-06-19 09:00:10",
        "2026-06-19 10:00:10",
        "2026-06-19 11:00:10",
        "2026-06-19 12:00:10",
        "2026-06-19 13:00:10",
        "2026-06-19 14:00:10",
        "2026-06-19 15:00:10",
        "2026-06-19 16:00:10",
        "2026-06-19 17:00:10",
        "2026-06-19 18:00:10",
        "2026-06-19 19:00:10",
        "2026-06-19 20:00:10",
        "2026-06-19 21:00:10",
        "2026-06-19 22:00:10",
        "2026-06-19 23:00:10"
    ],
    "jarak_sensor": [
        80.16, 78.95, 76.82, 74.64, 72.51, 70.18,
        68.73, 66.45, 64.28, 62.10, 60.34, 58.85,
        56.92, 54.77, 52.66, 50.48, 48.29, 46.18,
        44.02, 41.86, 39.73, 37.55, 35.38, 33.21,
        31.06, 29.47, 27.92, 26.84, 25.63, 24.91
    ],
    "Tinggi": [
        19.84, 21.05, 23.18, 25.36, 27.49, 29.82,
        31.27, 33.55, 35.72, 37.90, 39.66, 41.15,
        43.08, 45.23, 47.34, 49.52, 51.71, 53.82,
        55.98, 58.14, 60.27, 62.45, 64.62, 66.79,
        68.94, 70.53, 72.08, 73.16, 74.37, 75.09
    ],
    "nilai_hujan": [
        4095, 4095, 4095, 4095, 4095, 4095,
        4095, 4095, 4095, 4095, 4095, 4095,
        4095, 4095, 4095, 4095, 4095, 4095,
        4095, 4095, 4095, 4095, 4095, 4095,
        4095, 4095, 4095, 4095, 4095, 4095
    ]
})

# ============================================================
# 2. PREPROCESSING
# ============================================================

df["waktu"] = pd.to_datetime(df["waktu"])
df["Tinggi"] = pd.to_numeric(df["Tinggi"], errors="coerce")
df["nilai_hujan"] = pd.to_numeric(df["nilai_hujan"], errors="coerce")

df = df.sort_values("waktu").reset_index(drop=True)

# Untuk simulasi model "dengan curah hujan"
# Karena YL-83 bukan curah hujan mm, nilai_hujan dipakai sebagai fitur indikator.
# Agar arah lebih mudah dipahami: semakin kecil nilai_hujan = semakin basah.
df["indikator_hujan"] = 4095 - df["nilai_hujan"]

# ============================================================
# 3. MEMBUAT FITUR LAG TINGGI AIR
# ============================================================

for lag in [1, 2, 3, 6, 12, 24]:
    df[f"tinggi_lag{lag}"] = df["Tinggi"].shift(lag)

# ============================================================
# 4. MEMBUAT FITUR LAG HUJAN
# ============================================================

for lag in [1, 2, 3, 6, 12, 24]:
    df[f"hujan_lag{lag}"] = df["indikator_hujan"].shift(lag)

df["hujan_akumulasi_3jam"] = df["indikator_hujan"].rolling(3).sum()
df["hujan_akumulasi_6jam"] = df["indikator_hujan"].rolling(6).sum()
df["hujan_akumulasi_12jam"] = df["indikator_hujan"].rolling(12).sum()
df["hujan_akumulasi_24jam"] = df["indikator_hujan"].rolling(24).sum()

# Target prediksi satu langkah waktu ke depan
df["target"] = df["Tinggi"].shift(-1)

# ============================================================
# 5. FITUR MODEL
# ============================================================

fitur_tanpa_hujan = [
    "Tinggi",
    "tinggi_lag1",
    "tinggi_lag2",
    "tinggi_lag3",
    "tinggi_lag6",
    "tinggi_lag12",
    "tinggi_lag24"
]

fitur_dengan_hujan = [
    "Tinggi",
    "tinggi_lag1",
    "tinggi_lag2",
    "tinggi_lag3",
    "tinggi_lag6",
    "tinggi_lag12",
    "tinggi_lag24",
    "indikator_hujan",
    "hujan_lag1",
    "hujan_lag2",
    "hujan_lag3",
    "hujan_lag6",
    "hujan_lag12",
    "hujan_lag24",
    "hujan_akumulasi_3jam",
    "hujan_akumulasi_6jam",
    "hujan_akumulasi_12jam",
    "hujan_akumulasi_24jam"
]

# Hapus baris kosong akibat lag 24 dan target
df_model = df.dropna(subset=fitur_dengan_hujan + ["target"]).reset_index(drop=True)

print("Jumlah data awal:", len(df))
print("Jumlah data model setelah lag:", len(df_model))
display(df_model)

# ============================================================
# 6. DATA TRAINING DAN TESTING
# ============================================================

# Karena data drum hanya 30 baris dan setelah lag 24 tinggal 5 baris,
# seluruh data dipakai untuk demonstrasi model dashboard.
X_tanpa = df_model[fitur_tanpa_hujan]
X_dengan = df_model[fitur_dengan_hujan]
y = df_model["target"]

# ============================================================
# 7. MODEL XGBOOST TANPA CURAH HUJAN
# ============================================================

model_tanpa_hujan = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=30,
    max_depth=1,
    learning_rate=0.1,
    subsample=1.0,
    colsample_bytree=1.0,
    random_state=42,
    n_jobs=1
)

model_tanpa_hujan.fit(X_tanpa, y)
pred_tanpa_hujan = model_tanpa_hujan.predict(X_tanpa)

# ============================================================
# 8. MODEL XGBOOST DENGAN CURAH HUJAN
# ============================================================

model_dengan_hujan = XGBRegressor(
    objective="reg:squarederror",
    n_estimators=30,
    max_depth=1,
    learning_rate=0.1,
    subsample=1.0,
    colsample_bytree=1.0,
    random_state=42,
    n_jobs=1
)

model_dengan_hujan.fit(X_dengan, y)
pred_dengan_hujan = model_dengan_hujan.predict(X_dengan)

# ============================================================
# 9. EVALUASI MODEL
# ============================================================

def evaluasi_model(y_true, y_pred, nama_model):
    r2 = r2_score(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))

    return {
        "Model": nama_model,
        "R2": r2,
        "MAE": mae,
        "RMSE": rmse
    }

hasil_evaluasi = pd.DataFrame([
    evaluasi_model(y, pred_dengan_hujan, "XGBoost dengan Curah Hujan"),
    evaluasi_model(y, pred_tanpa_hujan, "XGBoost tanpa Curah Hujan")
])

print("Evaluasi Model")
display(hasil_evaluasi)

# ============================================================
# 10. TABEL HASIL PREDIKSI
# ============================================================

hasil_prediksi = pd.DataFrame({
    "waktu": df_model["waktu"],
    "tinggi_aktual": y.values,
    "prediksi_xgboost_dengan_curah_hujan": pred_dengan_hujan,
    "prediksi_xgboost_tanpa_curah_hujan": pred_tanpa_hujan
})

display(hasil_prediksi)

# ============================================================
# 11. GRAFIK PERBANDINGAN AKTUAL DAN HASIL PREDIKSI MODEL
# ============================================================

plt.figure(figsize=(12, 6))

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["tinggi_aktual"],
    marker="o",
    linewidth=2,
    label="Tinggi Air Aktual"
)

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["prediksi_xgboost_dengan_curah_hujan"],
    marker="o",
    linewidth=2,
    label="XGBoost dengan Curah Hujan"
)

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["prediksi_xgboost_tanpa_curah_hujan"],
    marker="o",
    linewidth=2,
    label="XGBoost tanpa Curah Hujan"
)

plt.title("Perbandingan Ketinggian Air Aktual dan Hasil Prediksi Model")
plt.xlabel("Waktu")
plt.ylabel("Ketinggian Air (cm)")
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ============================================================
# 12. SIMPAN GRAFIK
# ============================================================

plt.figure(figsize=(12, 6))

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["tinggi_aktual"],
    marker="o",
    linewidth=2,
    label="Tinggi Air Aktual"
)

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["prediksi_xgboost_dengan_curah_hujan"],
    marker="o",
    linewidth=2,
    label="XGBoost dengan Curah Hujan"
)

plt.plot(
    hasil_prediksi["waktu"],
    hasil_prediksi["prediksi_xgboost_tanpa_curah_hujan"],
    marker="o",
    linewidth=2,
    label="XGBoost tanpa Curah Hujan"
)

plt.title("Perbandingan Ketinggian Air Aktual dan Hasil Prediksi Model")
plt.xlabel("Waktu")
plt.ylabel("Ketinggian Air (cm)")
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()

plt.savefig("grafik_perbandingan_aktual_xgboost_dua_model.png", dpi=300)
plt.show()

# ============================================================
# 13. SIMPAN MODEL PKL
# ============================================================

joblib.dump(model_dengan_hujan, "xgboost_dengan_hujan.pkl")
joblib.dump(model_tanpa_hujan, "xgboost_tanpa_hujan.pkl")

# Untuk dashboard app.py kamu, nama file yang dibaca adalah:
# model/xgboost_lag_model.pkl
# Jadi model tanpa hujan disimpan juga dengan nama ini.
joblib.dump(model_tanpa_hujan, "xgboost_lag_model.pkl")

print("File model berhasil disimpan:")
print("1. xgboost_dengan_hujan.pkl")
print("2. xgboost_tanpa_hujan.pkl")
print("3. xgboost_lag_model.pkl")
print("4. grafik_perbandingan_aktual_xgboost_dua_model.png")

# ============================================================
# 14. DOWNLOAD FILE
# ============================================================

files.download("xgboost_dengan_hujan.pkl")
files.download("xgboost_tanpa_hujan.pkl")
files.download("xgboost_lag_model.pkl")
files.download("grafik_perbandingan_aktual_xgboost_dua_model.png")

"""
Scatter Plot Tinggi Air Acuan dan Terukur Prototipe
Sesuai Tabel 4.1 - Naskah Tugas Akhir Ilham Wijaya (122290088)
Jalankan di Google Colab
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

# ======================================================
# DATA SESUAI TABEL 4.1 (30 data, rentang 20-75 cm)
# ======================================================
acuan = np.array([
    20, 21, 23, 25, 27, 30, 31, 34, 36, 38,
    40, 41, 43, 45, 47, 50, 52, 54, 56, 58,
    60, 62, 65, 67, 69, 71, 72, 73, 74, 75
])

sensor = np.array([
    19.84, 21.05, 23.18, 25.36, 27.49, 29.82, 31.27, 33.55, 35.72, 37.90,
    39.66, 41.15, 43.08, 45.23, 47.34, 49.52, 51.71, 53.82, 55.98, 58.14,
    60.27, 62.45, 64.62, 66.79, 68.94, 70.53, 72.08, 73.16, 74.37, 75.09
])

# ======================================================
# REGRESI LINIER & METRIK EVALUASI
# ======================================================
X = acuan.reshape(-1, 1)
y = sensor

model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)

r2 = r2_score(y, y_pred)
mae = mean_absolute_error(y, y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

# Galat absolut & persentase galat (terhadap acuan langsung, bukan garis regresi)
galat_absolut = np.abs(sensor - acuan)
persen_galat = (galat_absolut / acuan) * 100
akurasi = 100 - persen_galat

print("=== Ringkasan Hasil ===")
print(f"Rata-rata galat absolut : {galat_absolut.mean():.2f} cm")
print(f"Std galat absolut       : {galat_absolut.std():.2f} cm")
print(f"Rata-rata %galat absolut: {persen_galat.mean():.2f} %")
print(f"Rata-rata akurasi       : {akurasi.mean():.2f} %")
print(f"RMSE (regresi)          : {rmse:.2f} cm")
print(f"R^2 (regresi)           : {r2:.4f}")

# ======================================================
# PLOT
# ======================================================
plt.figure(figsize=(8, 6))

# Titik data pengukuran sensor
plt.scatter(acuan, sensor, color='royalblue', s=50, label='Data pengukuran sensor', zorder=3)

# Garis regresi linier
x_line = np.linspace(acuan.min(), acuan.max(), 100)
y_line = model.predict(x_line.reshape(-1, 1))
plt.plot(x_line, y_line, color='royalblue', linewidth=1.5,
         label=f'Regresi linier, R² = {r2:.4f}')

# Garis ideal y = x
plt.plot(x_line, x_line, color='orange', linestyle='--', linewidth=1.5,
         label='Garis ideal y = x')

plt.title('Scatter Plot Tinggi Air Acuan dan Terukur Prototipe', fontsize=13)
plt.xlabel('Tinggi Air Acuan (cm)')
plt.ylabel('Tinggi Air Terukur Sensor (cm)')
plt.legend(loc='upper left')
plt.grid(True, alpha=0.4)
plt.tight_layout()

plt.savefig('scatter_akurasi_prototipe.png', dpi=300)
plt.show()